import yaml

from snakemake.utils import min_version, validate

min_version("8.10")


# Load the example configuration. This will be overridden by users.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)


# Add all your includes here.
include: "rules/automatic.smk"
include: "rules/process_data.smk"
include: "rules/calculate_demand.smk"

# Get necessary params to produce the final files
scenario_name = config["required"]["scenario_name"]
population_ref_year = config["required"]["population_ref_year"]

# Add additional files to be delivered alongside the workflow here.
# This is needed e.g. for python code files that are never
# explicitly used as a script or input in a snakemake rule.
# e.g.: workflow.source_path("scripts/_utils.py")

rule all:
    message:
        "Generate both demand files as given."
    input:
        vRES_demand=expand("results/demand/demand_vRES_{population_ref_year}_{scenario_name}.csv",
            population_ref_year=population_ref_year, scenario_name=scenario_name),
        GH2_demand=expand("results/demand/demand_GH2_{population_ref_year}_{scenario_name}.csv",
            population_ref_year=population_ref_year, scenario_name=scenario_name),
    default_target: True

